# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: JacktoseIntolerant GitHub
email: P1h3r1e3d13 at gmail doc com
description: > # this means to ignore newlines until "baseurl:"
    A test page for Jacktose Intolerant to play with
    GitHub Pages, Jekyll, and random web stuff.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://github.jacktose.com" # the base hostname & protocol for your site
#twitter_username: 
github_username:  JacktoseIntolerant

# Build settings
markdown:    kramdown
highlighter: rouge
permalink:   /:year/:title
